version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: chart.js
    versions:
    - 3.0.2
    - 3.1.0
    - 3.1.1
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: jest-when
    versions:
    - 3.1.0
    - 3.2.0
  - dependency-name: tape
    versions:
    - 5.1.1
    - 5.2.0
