language: node_js	
node_js:	
  - '6'	
  - '8'	
  - '10'	
before_install:	
  - npm install -g grunt-cli	
before_script:	
  - grunt build	
  - npm i -g surge
script: 
  - npm test
  - ./pr_deploy.sh
