
# Using a sudo enabled, Linux trusty distribution, VM
sudo: required
dist: trusty

# versions of node to use
language: node_js
node_js:
- 6

# Running javascript tests in browser
before_install:
#set CHROME_BIN as chromium-browser
- export CHROME_BIN=chromium-browser
#set up a fake DISPLAY
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

# Build a production build of the project
before_script:
  - npm i -g
  - npm i -g grunt
  - grunt build
  - npm i -g surge

# Check for coverage, and linting
script:
  - ./pr_deploy.sh

# Notify codecov, deploy to surge
after_success:
- echo "success"

# enable node_modules dir to avoid re-download everytime
cache:
    bundler: true
    directories:
    - node_modules